name: deploy app

on:
  push:
    branches: [master]
    paths:
      - 'posts/**'
      - '.vuepress/**'
      - 'plugins/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install packages
        run: npm install

      - name: Builds & deploy with gh-pages
        run: npm run deploy -- -r https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: kisstar.github.io

      - name: Set ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{GITEE_TOKEN}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{GITEE_IP}}" >> ~/.ssh/known_hosts
        env:
          GITEE_IP: 212.64.63.190
          GITEE_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}

      - name: Deploy with gh-pages
        run: |
          gh-pages -d .vuepress/dist -b master -r git@gitee.com:dongwanhong/${GITEE_REPOSITORY}.git
        env:
          GITEE_REPOSITORY: dongwanhong

      - name: Remove ssh key
        run: rm -rf ~/.ssh
