name: deploy app

on:
  push:
    branches: [master]
    paths:
      - 'posts/**'
      - '.vuepress/**'
      - 'plugins/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install packages
        run: npm install

      - name: Builds the app for production
        run: npm run build

      - name: Set git user information
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
        env:
          USER_NAME: kisstar
          USER_EMAIL: dwh.chn@foxmail.com

      - name: Deploy with gh-pages for GitHub
        run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/kisstar/${GITHUB_REPOSITORY}.git
          npx gh-pages -d .vuepress/dist -b master
          git remote remove origin
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPOSITORY: kisstar.github.io

      - name: Set ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "$GITEE_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}

      - name: Deploy with gh-pages for Gitee
        run: |
          git remote add origin git@gitee.com:dongwanhong/${GITEE_REPOSITORY}.git
          npx gh-pages -d .vuepress/dist -b master
          git remote remove origin
        env:
          GITEE_REPOSITORY: dongwanhong

      - name: Remove ssh key
        run: rm -rf ~/.ssh
