name: deploy

on:
  push:
    branches: [master]
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install packages
        run: pnpm install

      - name: Builds the app for production
        run: pnpm run build
